[package]
name = "algorithms4"
description = "A rust implementation of the 4th edition of Algorithms by R. Sedgewick and K. Wayne."
version = "0.0.1"
edition = "2024"
rust-version = "1.88.0"

readme = "README.md"
license = "MIT"
repository = "https://github.com/tobiO0310/algorithms4"
keywords = ["algorithms", "algs4"]

[dependencies]
num = "0.4.3"
rand = "0.10.1"

[dev-dependencies]
criterion = "0.7.0"
pastey = { package = "pastey", version = "0.2.3" }

[[bench]]
name = "union_find"
harness = false
